### ISSUE TITLE
HTML/CSS

### ISSUE THREAD

**Issue by perguth** [blob-stream/features#11]
Create basic UI with creator.ionic.io

**Comment by LilK3ks** [comment]
- blob-button does not work.
  => Create new page and link it!

**Comment by perguth** [comment]
Added in https://github.com/blob-stream/ionic-node/pull/1/commits/d4299786915c80299d53bf65452cbc7cac11cac6

**Comment by LilK3ks** [comment]
It shouldn't be a tabbar. Maybe ionic footer

**Comment by LilK3ks** [comment]
Added in https://github.com/blob-stream/ionic-node/commit/a258466683999d7b160de36b280033bfba569139

**Comment by LilK3ks** [comment]
Added Pguth Menu in https://github.com/blob-stream/ionic-node/commit/8a54dc2a07f2e96cfce1eaf98253f5e4b604c47a

**Comment by LilK3ks** [comment]
Added back button in https://github.com/blob-stream/ionic-node/commit/9ef3ab5bbe3f93b3f1dc7f0fdd56eebe0379f5db

**Comment by LilK3ks** [comment]
Centering the "+Add a blob" - button in https://github.com/blob-stream/ionic-node/commit/a177f0c9a866067ad7a5f73c87caca6831c6e747
